apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo
  labels:
    name: kubernetes-demo
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      name: metrics
  selector:
    name: kubernetes-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kubernetes-demo
  name: kubernetes-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      name: kubernetes-demo
  template:
    metadata:
      labels:
        name: kubernetes-demo
    spec:
      containers:
        - image: kubernetes-demo:latest
          imagePullPolicy: Never
          name: kubernetes-demo
          ports:
            - containerPort: 8080